In [1]:
import pandas as pd
from sklearn import preprocessing
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.linear_model import SGDClassifier
import numpy as np

np.random.seed(3407)

In [2]:
df = pd.read_csv("seattle-weather.csv")
df

            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [3]:
le = preprocessing.LabelEncoder()
df["weather"] = le.fit_transform(df["weather"])
df

            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7        0
1     2012-01-02           10.9      10.6       2.8   4.5        2
2     2012-01-03            0.8      11.7       7.2   2.3        2
3     2012-01-04           20.3      12.2       5.6   4.7        2
4     2012-01-05            1.3       8.9       2.8   6.1        2
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9        2
1457  2015-12-28            1.5       5.0       1.7   1.3        2
1458  2015-12-29            0.0       7.2       0.6   2.6        1
1459  2015-12-30            0.0       5.6      -1.0   3.4        4
1460  2015-12-31            0.0       5.6      -2.1   3.5        4

[1461 rows x 6 columns]

In [4]:
scaler = preprocessing.StandardScaler()
X_train = df.iloc[0:1061].drop(["weather", "date"], axis=1)
X_train = pd.DataFrame(data=scaler.fit_transform(X_train), columns=X_train.columns)
X_train

      precipitation  temp_max  temp_min      wind
0         -0.470248 -0.479315 -0.626347  0.990984
1          1.270699 -0.779524 -1.062471  0.854195
2         -0.342472 -0.629419 -0.190223 -0.650493
3          2.772066 -0.561190 -0.507404  0.990984
4         -0.262612 -1.011503 -1.062471  1.948513
...             ...       ...       ...       ...
1056      -0.390388 -0.943274 -0.289342  0.990984
1057       1.430419 -0.479315 -0.507404  1.264564
1058      -0.262612 -0.629419 -0.745290  0.375431
1059       2.452626 -0.329211  0.245901  0.854195
1060      -0.422332 -0.179107  0.800969  0.443825

[1061 rows x 4 columns]

In [5]:
y_train = df.iloc[0:1061]["weather"]
y_train

0       0
1       2
2       2
3       2
4       2
       ..
1056    2
1057    2
1058    2
1059    2
1060    2
Name: weather, Length: 1061, dtype: int64

In [6]:
X_test = df.iloc[1061:].drop(["weather", "date"], axis=1)
X_test = pd.DataFrame(data=scaler.transform(X_test), columns=X_test.columns)
X_test

     precipitation  temp_max  temp_min      wind
0         0.056828 -0.260982  0.701850  2.290487
1         5.008144 -0.479315 -0.963352  1.743328
2         0.104744 -1.625566 -2.469963  1.401354
3        -0.470248 -1.843899 -2.588906  0.785800
4        -0.470248 -1.625566 -2.251901 -0.718888
..             ...       ...       ...       ...
395       0.903343 -1.625566 -1.280534 -0.240123
396      -0.230668 -1.543691 -1.280534 -1.334442
397      -0.470248 -1.243482 -1.498596 -0.445308
398      -0.470248 -1.461816 -1.815777  0.101851
399      -0.470248 -1.461816 -2.033839  0.170246

[400 rows x 4 columns]

In [7]:
y_test = df.iloc[1061:]["weather"]
y_test

1061    2
1062    2
1063    3
1064    4
1065    4
       ..
1456    2
1457    2
1458    1
1459    4
1460    4
Name: weather, Length: 400, dtype: int64

In [8]:
clf = SGDClassifier(n_jobs=-1, max_iter=2000)
clf.fit(X_train, y_train)
pred = clf.predict(X_test)
accuracy_score(y_test, pred)

0.725

In [ ]:
parameters = {
    "loss": (
        "hinge",
        "log_loss",
        "log",
        "modified_huber",
        "squared_hinge",
        "perceptron",
    ),
    "penalty": ("l2", "l1", "elasticnet"),
    "alpha": (0.1, 0.01, 0.001, 0.0001, 0.00001),
    "tol": (0.1, 0.01, 0.001, 0.0001, 0.00001),
    "epsilon": (0.1, 0.01, 0.001, 0.0001, 0.00001),
    "learning_rate": ("constant", "optimal", "invscaling", "adaptive"),
}
gs = GridSearchCV(SGDClassifier(max_iter=2000), parameters, n_jobs=-1)
gs.fit(X_train, y_train)

In [10]:
gs.best_params_

{'alpha': 0.001,
 'epsilon': 1e-05,
 'learning_rate': 'optimal',
 'loss': 'modified_huber',
 'penalty': 'l1',
 'tol': 0.001}

In [11]:
pred = gs.predict(X_test)
accuracy_score(y_test, pred)

0.83

In [12]:
parameters = {
    "C": (0.01, 0.1, 1, 10, 100, 1000),
    "kernel": ("linear", "poly", "rbf", "sigmoid"),
    "gamma": ("scale", "auto"),
}
gs = GridSearchCV(SVC(), parameters, n_jobs=-1)
gs.fit(X_train, y_train)

GridSearchCV(estimator=SVC(), n_jobs=-1,
             param_grid={'C': (0.01, 0.1, 1, 10, 100, 1000),
                         'gamma': ('scale', 'auto'),
                         'kernel': ('linear', 'poly', 'rbf', 'sigmoid')})

In [13]:
gs.best_params_

{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}

In [14]:
pred = gs.predict(X_test)
accuracy_score(y_test, pred)

0.83

In [15]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes=(500,), max_iter=2000).fit(X_train, y_train)
pred = clf.predict(X_test)
accuracy_score(y_test, pred)

0.8325

In [16]:
from sklearn.ensemble import GradientBoostingClassifier

clf = GradientBoostingClassifier(n_estimators=1000).fit(X_train, y_train)
pred = clf.predict(X_test)
accuracy_score(y_test, pred)

0.7975

In [17]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=2000).fit(X_train, y_train)
pred = clf.predict(X_test)
accuracy_score(y_test, pred)

0.8275

In [ ]:
from catboost import CatBoostClassifier

clf = CatBoostClassifier().fit(X_train, y_train)
pred = clf.predict(X_test)

In [19]:
accuracy_score(y_test, pred)

0.825

In [ ]:
parameters = {
    "depth": [4, 5, 6, 7, 8, 9, 10],
    "learning_rate": [0.01, 0.02, 0.03, 0.04, 0.1],
    "iterations": [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    "l2_leaf_reg": [1, 3, 5, 7, 9],
}
clf = CatBoostClassifier()
grid_search_result = clf.grid_search(parameters, X=X_train, y=y_train)

In [21]:
grid_search_result["params"]

{'depth': 8, 'l2_leaf_reg': 1, 'iterations': 100, 'learning_rate': 0.1}

In [22]:
from catboost import CatBoostClassifier

clf = CatBoostClassifier(**grid_search_result["params"]).fit(X_train, y_train)
pred = clf.predict(X_test)
accuracy_score(y_test, pred)

0:	learn: 1.3556536	total: 12.3ms	remaining: 1.22s
1:	learn: 1.1930172	total: 15.7ms	remaining: 771ms
2:	learn: 1.0748893	total: 17.9ms	remaining: 578ms
3:	learn: 0.9810387	total: 19.6ms	remaining: 471ms
4:	learn: 0.9062993	total: 22.3ms	remaining: 424ms
5:	learn: 0.8462163	total: 25.1ms	remaining: 393ms
6:	learn: 0.7994736	total: 27.7ms	remaining: 369ms
7:	learn: 0.7571785	total: 29.9ms	remaining: 344ms
8:	learn: 0.7194132	total: 32.7ms	remaining: 331ms
9:	learn: 0.6848448	total: 34.9ms	remaining: 314ms
10:	learn: 0.6562861	total: 37.1ms	remaining: 300ms
11:	learn: 0.6314848	total: 39.6ms	remaining: 291ms
12:	learn: 0.6107388	total: 41.8ms	remaining: 279ms
13:	learn: 0.5946732	total: 43.9ms	remaining: 270ms
14:	learn: 0.5781086	total: 46.2ms	remaining: 262ms
15:	learn: 0.5611974	total: 48.2ms	remaining: 253ms
16:	learn: 0.5473708	total: 50.9ms	remaining: 248ms
17:	learn: 0.5326800	total: 53.5ms	remaining: 244ms
18:	learn: 0.5227112	total: 55.8ms	remaining: 238ms
19:	learn: 0.5140844	total: 58.7ms	remaining: 235ms
20:	learn: 0.5046113	total: 61.6ms	remaining: 232ms
21:	learn: 0.4963721	total: 64.1ms	remaining: 227ms
22:	learn: 0.4874340	total: 66.2ms	remaining: 222ms
23:	learn: 0.4797875	total: 68.8ms	remaining: 218ms
24:	learn: 0.4710777	total: 71.7ms	remaining: 215ms
25:	learn: 0.4646908	total: 74ms	remaining: 211ms
26:	learn: 0.4598487	total: 77ms	remaining: 208ms
27:	learn: 0.4549282	total: 79.9ms	remaining: 205ms
28:	learn: 0.4489338	total: 81.9ms	remaining: 201ms
29:	learn: 0.4454136	total: 84.9ms	remaining: 198ms
30:	learn: 0.4393356	total: 87ms	remaining: 194ms
31:	learn: 0.4354266	total: 89.3ms	remaining: 190ms
32:	learn: 0.4306523	total: 91.8ms	remaining: 186ms
33:	learn: 0.4263561	total: 94.2ms	remaining: 183ms
34:	learn: 0.4239246	total: 96.4ms	remaining: 179ms
35:	learn: 0.4200422	total: 98.5ms	remaining: 175ms
36:	learn: 0.4168389	total: 100ms	remaining: 171ms
37:	learn: 0.4132692	total: 103ms	remaining: 168ms
38:	learn: 0.4095516	total: 106ms	remaining: 165ms
39:	learn: 0.4064078	total: 108ms	remaining: 162ms
40:	learn: 0.4042177	total: 112ms	remaining: 161ms
41:	learn: 0.4016533	total: 114ms	remaining: 157ms
42:	learn: 0.3975468	total: 116ms	remaining: 154ms
43:	learn: 0.3957912	total: 119ms	remaining: 151ms
44:	learn: 0.3932372	total: 121ms	remaining: 148ms
45:	learn: 0.3909974	total: 123ms	remaining: 145ms
46:	learn: 0.3875602	total: 126ms	remaining: 142ms
47:	learn: 0.3855800	total: 128ms	remaining: 138ms
48:	learn: 0.3840356	total: 130ms	remaining: 136ms
49:	learn: 0.3820411	total: 133ms	remaining: 133ms
50:	learn: 0.3800134	total: 135ms	remaining: 129ms
51:	learn: 0.3788285	total: 137ms	remaining: 126ms
52:	learn: 0.3770124	total: 139ms	remaining: 123ms
53:	learn: 0.3747123	total: 141ms	remaining: 120ms
54:	learn: 0.3718446	total: 143ms	remaining: 117ms
55:	learn: 0.3703577	total: 145ms	remaining: 114ms
56:	learn: 0.3691117	total: 148ms	remaining: 111ms
57:	learn: 0.3674870	total: 150ms	remaining: 109ms
58:	learn: 0.3653557	total: 152ms	remaining: 106ms
59:	learn: 0.3631156	total: 155ms	remaining: 103ms
60:	learn: 0.3613859	total: 157ms	remaining: 100ms
61:	learn: 0.3603829	total: 159ms	remaining: 97.5ms
62:	learn: 0.3589758	total: 161ms	remaining: 94.6ms
63:	learn: 0.3566126	total: 164ms	remaining: 92.2ms
64:	learn: 0.3548725	total: 166ms	remaining: 89.5ms
65:	learn: 0.3523744	total: 168ms	remaining: 86.8ms
66:	learn: 0.3508931	total: 171ms	remaining: 84ms
67:	learn: 0.3497421	total: 173ms	remaining: 81.3ms
68:	learn: 0.3480712	total: 175ms	remaining: 78.7ms
69:	learn: 0.3461240	total: 178ms	remaining: 76.1ms
70:	learn: 0.3443415	total: 180ms	remaining: 73.5ms
71:	learn: 0.3426618	total: 183ms	remaining: 71ms
72:	learn: 0.3411816	total: 185ms	remaining: 68.2ms
73:	learn: 0.3400713	total: 187ms	remaining: 65.8ms
74:	learn: 0.3381231	total: 190ms	remaining: 63.2ms
75:	learn: 0.3361302	total: 191ms	remaining: 60.5ms
76:	learn: 0.3346007	total: 193ms	remaining: 57.7ms
77:	learn: 0.3330135	total: 196ms	remaining: 55.2ms
78:	learn: 0.3309615	total: 198ms	remaining: 52.6ms
79:	learn: 0.3295704	total: 200ms	remaining: 50ms
80:	learn: 0.3274635	total: 203ms	remaining: 47.7ms
81:	learn: 0.3258689	total: 206ms	remaining: 45.3ms
82:	learn: 0.3230542	total: 210ms	remaining: 43.1ms
83:	learn: 0.3210571	total: 213ms	remaining: 40.5ms
84:	learn: 0.3199194	total: 216ms	remaining: 38ms
85:	learn: 0.3179430	total: 218ms	remaining: 35.5ms
86:	learn: 0.3157596	total: 221ms	remaining: 33ms
87:	learn: 0.3141581	total: 223ms	remaining: 30.4ms
88:	learn: 0.3114014	total: 226ms	remaining: 27.9ms
89:	learn: 0.3102701	total: 229ms	remaining: 25.4ms
90:	learn: 0.3085368	total: 231ms	remaining: 22.8ms
91:	learn: 0.3063864	total: 233ms	remaining: 20.3ms
92:	learn: 0.3042907	total: 236ms	remaining: 17.8ms
93:	learn: 0.3023956	total: 239ms	remaining: 15.3ms
94:	learn: 0.3012070	total: 243ms	remaining: 12.8ms
95:	learn: 0.2996466	total: 245ms	remaining: 10.2ms
96:	learn: 0.2980298	total: 247ms	remaining: 7.65ms
97:	learn: 0.2961954	total: 250ms	remaining: 5.09ms
98:	learn: 0.2941954	total: 252ms	remaining: 2.54ms
99:	learn: 0.2929665	total: 255ms	remaining: 0us

0.8375